[package]
authors = ["Frequency"]
description = "A package that defines common helper modules used in Frequency"
edition = "2021"
homepage = "https://frequency.xyz"
license = "Apache-2.0"
name = "common-helpers"
publish = false
repository = "https://github.com/LibertyDSNP/frequency/"
version = "0.0.1-rc1+polkadot0.9.36"

[package.metadata.docs.rs]
targets = ['x86_64-unknown-linux-gnu']

[dependencies]
apache-avro = { version = "0.14.0", features = ["snappy"] }
thiserror = "1.0.34"
jsonrpsee = { version = "0.16.2", features = ["client-core", "server", "macros"] }
sp-runtime = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v0.9.36" }
sp-api = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v0.9.36" }
sp-io = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v0.9.36" }
common-primitives = { path = "../primitives", default-features = false }

[features]
default = ['std']
std = ['sp-runtime/std', 'sp-api/std', 'sp-io/std', 'common-primitives/std']
